apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: accountmanager
  name: accountmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountmanager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accountmanager
    spec:
      containers:
      - image: lrzeszotarski/accountmanager
        name: accountmanager
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: accountmanager
  name: accountmanager
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: accountmanager
  type: ClusterIP
status:
  loadBalancer: {}
